siteorigin/so-css

so-css.php

Disable NextGen Gallery weird resource manager to prevent it messing with script and template load order. To resolve GH-4.

NextGen Gallery bug.

---

js/inspector.js

To resolve GH-12.
Add classes on `body` element to selectors window.
Extracted common specificity calculation into function.

Display all classes on body.

---

css/admin.css
css/admin.less
tpl/page.php

When viewing revision, change save button text

---

so-css.php

[Related](https://wordpress.org/support/topic/the-css-file-is-never-loaded)

Change stylesheet hook to wp_enqueue_scripts

---

js/editor.js

This PR requires siteorigin/siteorigin-premium#215

Detect changes made to Web Font Selector and set up onchange

---

css/admin.css
css/admin.less

Resolves #92.
Also resolves alignment of the Decoration > Background image upload button.

Form styling fixes

---

css/admin.css
css/admin.less
tpl/page.php

Move Save CSS button to sidebar

---

js/editor.js
so-css.php
tpl/page.php

Fix saving issue by moving form

---

tpl/js-templates.php

Resolve https://github.com/siteorigin/so-css/issues/111

Add Class to Font Family field to allow for changes

---

js/editor.js

Resolve https://github.com/siteorigin/so-css/issues/117

Correctly add backgrund image to CSS

---

js/editor.js
js/inspector.js

Resolve https://github.com/siteorigin/so-css/issues/90

Resolve WC Tabs display issue

---

js/inspector.js

Resolve https://github.com/siteorigin/so-css/issues/25

Inspector: Highlight important classes

---

js/editor.js

Resolve https://github.com/siteorigin/so-css/issues/63
To test this, remove all CSS and then attempt to right click paste on a non-active line. You previously weren't given the option to right click paste.

Editor: Allow Right Click Paste Anywhere

---

css/admin.css
css/admin.less

Visual View: Vertically Center Selector

---

tpl/page.php

This PR will add titles to the toolbar buttons.

Toolbar Button Titles

---

css/admin.css
css/admin.less

This PR:
- Removes the grey border from the Save Button.
- Sets direct dimensions for the buttons to ensure they're consistently sized.

Button Adjustments

---

inc/controller-config.php
so-css.php
tpl/js-templates.php
tpl/page.php

Follow up to https://github.com/siteorigin/so-css/pull/145 covering more strings.

l10n: `esc_html` to `esc_html__` pt2

---

js/editor.js

This will result in the editor never changing height.

Fixed Height Editor

---

js/css.js
package-lock.json
package.json
so-css.php

Resolve https://github.com/siteorigin/so-css/issues/155
This PR will prevent the escaping of the following CSS:
```
#home-hero .sow-slider-base::after {
content: "";
width: 100%;
height: 10px;
background: red;
position: relative;
display: table;
}
```
Please add the above CSS using the Expanded Editor and save using both regular saving and Ajax.

Update css.js to resolve unintended escaping & Prevent Unintended Slashes During Ajax Save

---

tpl/page.php

This PR will ensure the current theme is selected in the Editor Theme drop-down.

Editor Theme: Show Current Theme

---

so-css.php

This PR will resolve https://github.com/siteorigin/so-css/issues/162

Ensure WP Filesystem is Setup
