js/editor.js
It is necessary to alt click _on_ the editor for the copy/paste context options to be available, so this pads the initial value with newlines so that the editor takes up 15 lines, which should be approximately all the initial whitespace.
=> Gh 20 context menu copypaste

so-css.php
plugin_dir_url() adds a slash by default. Adding another slash can cause issues on certain setups (such as Windows or Google AppEngine.
See: siteorigin/so-widgets-bundle#325
=> Removed leading slash in paths after plugin_dir_url()

so-css.php
To resolve #17. Simply stores the CSS as a file in uploads dir and uses the revision timestamp when enqueuing as an attempt at cache busting.
=> Save CSS to file

so-css.php
Resolves #69 
This issue will fix the following warnings:
(! ) Warning: krsort() expects parameter 1 to be array, boolean given in C:\wamp64\www\siteorigin\wp-content\plugins\so-css\so-css.php on line 485
( ! ) Warning: array_keys() expects parameter 1 to be array, boolean given in C:\wamp64\www\siteorigin\wp-content\plugins\so-css\so-css.php on line 486
Reported [here](https://siteorigin.com/thread/error-from-siteorigin-css/) and [here](https://siteorigin.com/thread/error-from-siteorigin-css-2). The issue was previously reported elsewhere but at the time it appeared to be user specific.
=> Fix timestamp notice on certan setups

so-css.php
Resolves compatibility issues with all YITH plugins. [Related](https://wordpress.org/support/topic/any-yith-plugin-breaks-siteorigin-css/#post-10679579)
=> Prefix so-css for all codemirror assets

so-css.php
This PR fixes #95. While a direct fix to the warning is possible, get_theme_css() is never actually used anywhere so it's best that it gets removed to prevent further issues.
=> Remove get_theme_css()

css/admin.css, css/admin.less
Currently, if you select the Opacity field, you'll see the following:
This PR reduces the width of the field in question. If there are further instances of this issue then we can perhaps look into a more holistic approach vs adding a single exception/override as I've done here.
=> Reduced the Opacity field width

so-css.php
The issue was linked to \A. That's valid but the regex library PHP is now using is apparently much stricter the rexex so the placement of the \A was now invalid due to it not being at the start.
https://stackoverflow.com/questions/57829977/error-when-removing-css-comments-via-regex
The regex that person is using is exactly the same as SiteOrigin CSS was using. It's from:
https://stackoverflow.com/questions/1581049/preg-replace-out-css-comments/1581063#1581063
I swapped out the now invalid regex with the ones suggested by that user:
`"`(\A|[\n;]+)/\*[^*]*\*+(?:[^/*][^*]*\*+)*/`"=>"$1"
`I tried the modified version on PHP 7.3, 7.2, and 7.1. It worked as expected - comments were still being spaced out.
Resolves https://github.com/siteorigin/so-css/issues/97.
=> Replace CSS Comment patterns with PHP 7.4 friendly patterns

so-css.php, tpl/page.php
This PR resolves https://github.com/siteorigin/so-css/issues/109.
I didn't realize that SiteOrigin CSS was saving when inside of the [admin_menu](https://developer.wordpress.org/reference/hooks/admin_menu/) hook. [This change](https://github.com/siteorigin/so-css/pull/108/commits/e43b01ad422f4a96b7c013e133789ba7cc035766#diff-1444ac476d5226ed00e47994a46e7a35R268) resulted in this issue as that would result in the `check_admin_referer` check triggering which will always fail outside of SiteOrigin CSS.
I checked SiteOrigin CSS saving is still working as expected and that the buttons plugin is saving without issue now.
=> Rename custom_css textarea to prevent conflicts

css/admin.css, css/admin.less, js/editor.js, tpl/page.php
This PR changes the paragraph class name that wraps the submit button. A user reported issues with the generic class name.
Ref: https://wordpress.org/support/topic/add-float-none-to-save-css-button/.
=> Updated button container class name

js/editor.js, js/inspector.js
This PR is to remove jQuery Migrate Notices and ensure compatibility with newer versions of jQuery. Please note that the Web Font Selector dropdown will trigger a notice - that has to be fixed in a different PR.
=> jQuery: Replace shorthand events with on/trigger

js/editor.js
This resulted in the scrollbar height never being set. In turn, the SiteOrigin CSS Editor is the full height rather than condensed. This used to fail gracefully with older versions of jQuery, but as of WordPress 5.6 (and the jQuery update), it doesn't anymore.
=> Resolve 5.6 scrollbar not being added

css/admin.less, js/editor.js, so-css.php
This is only possible in 4.9 or later so a local version of CM is still bundled to maintain compatibility.
I'm getting better overall performance with the newer versions of CM so that should help users who have previously reported performance-related issues.
=> Use WP version of CodeMirror

js/editor.js
This PR prevents a JavaScript error that occurs if a user dequeues `socss-codemirror-show-hint`. To test this comment [this line](https://github.com/siteorigin/so-css/blob/1.2.11/so-css.php#L326 out.
=>  Only show hints/autocomplete when showHint is available

so-css.php
This PR will make SO CSS always load the CodeMirror theme we use regardless of whether we're using the WordPress or bundled version of CodeMirror.
Before:
After:
=> Always output local CodeMirror Theme styling

js/inspector.js
The [Photo Gallery](https://wordpress.org/plugins/photo-gallery/) plugin is having `.is( ':hover' ) (which isn't technically valid anymore) so this commit changes to a different method of confirming if the clicked item is the inspector or not.
To test this PR:
- Set up a basic Photo Gallery and add it to any page. (no setting adjustments are required) (this may not actually be required, but I wasn't able to replicate it until I had done this)
-  Open the expanded editor and try and navigate to a different page.
=> Resolve Photo Gallery Conflict

inc/controller-config.php, js/editor.js, tpl/js-templates.php
Resolve https://github.com/siteorigin/so-css/issues/98
This setting is just below the Border setting in the Decoration tab.
This required extending the slides field to allow for radius buttons.
=> Add Border Radius Setting

js/inspector.js
This PR resolves the issue reported [here](https://wordpress.org/support/topic/navigate-to-the-page-in-question-does-not-work/). This issue wasn't introduced in https://github.com/siteorigin/so-css/pull/130 (as I can't replicate it while using that direct build) but the reasoning behind that PR is here as this PR supersedes it. This means that this PR must be tested against the Photo Gallery plugin to ensure compatibility.
To test this PR:
- Confirm that you're able to navigate to other pages and the general inspector works as expected.
- Run the tests outlined for https://github.com/siteorigin/so-css/pull/130
=> Resolve Active Link Detection Issue That Prevented Navigation

inc/controller-config.php, so-css.php
This PR resolves the issue [reported here](https://wordpress.org/support/topic/losing-the-most-of-ui-strings-for-l10n/), and allows [the recently altered strings](https://github.com/siteorigin/so-css/pull/142) to be translated.
=> l10n: `esc_html` to `esc_html__`

tpl/page.php
This PR resolves a formatting issue with a premium teaser:
I've looked around and wasn't able to identify any other text affected by this issue.
=> Correct Formatting in Teaser

css/admin.css, css/admin.less, tpl/page.php
This PR adds an additional save button below the editor. Its positioning is based on where the save button used to be.
=> Add Additional Save Button Below Editor

css/admin.css, css/admin.less, js/editor.js
This was broken due to a CodeMirror Library change in a recent WP update. :disappointed:  (unclear on the specific WP update)
=> Restore Scrollbar and Automatic Container Sizing Size

tpl/page.php
This PR will remove the second save button and it's made due to the now completely fixed height CSS CodeMirror Textarea.
=> Remove Second Save Button

so-css.php
Resolves https://github.com/siteorigin/so-css/issues/160
This is done by introducing the `siteorigin_custom_css_file` filter which allows you to specify the URI for a custom CSS file (will be created if it doesn't exist) and URL for the file for SiteOrigin CSS to load - if the URL is empty, the developer will need to manually load the CSS file.
`siteorigin_custom_css_file` example::
```
add_filter( 'siteorigin_custom_css_file', function( $file ) {
return array(
'file' => get_template_directory() . '/rtl.css',
'url' => get_template_directory_uri() . '/rtl.css',
);
} );
```
(test using Vantage or any other theme that includes rtl.css)
This PR also introduces `siteorigin_css_enqueue_css` which controls whether SiteOrigin CSS will enqueue the custom CSS file. It can also be used by the user …
=> Allow Custom CSS File Editing
